from . import hr_attendance
from . import hr_contract
from . import hr_leave
from . import hr_payslip
from . import hr_planning_payslip
from . import planning_slot
from . import planning_slot_ext
from . import recargo_rule
from . import regenerate_work
from . import res_config
