{
    "name": "Payroll Rules Planning",
    "summary": "Horarios, novedades de nomina y recargos sobre work entries.",
    "version": "18.0.2.0.0",
    "author": "Navegasoft",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "hr",
        "hr_contract",
        "hr_payroll",
        "hr_attendance",
        "hr_holidays",
        "hr_holidays_attendance",
        "planning",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/rules.xml",
        "data/work_entry_types.xml",
        "data/rules_payslip.xml",
        "views/hr_contract.xml",
        "views/hr_leave_type.xml",
        "views/hr_work_entry_type.xml",
        "views/planning.xml",
        "views/res_company.xml",
        "views/recargo_rule.xml",
        "views/slot_template.xml",
    ],
}
