from . import hr_employee
from . import hr_contract
from . import res_company
from . import hr_certified_concept
from . import hr_salary
from . import res_config_settings
from . import hr_employee_functions
from . import hr_employee_program
from . import hr_leave_type
from . import mail_activity_type
from . import calendar_event
from . import calendar_attendee
from . import mail_activity
from . import hr_salary_rule